### PR TITLE
Implemented external pressure/density condition

### PR DESCRIPTION
**Pull request by calvin-sykes**
Originally, the code sets the density/pressure profiles by requiring that the total gas mass matches that given by Mvir * fbar, where fbar is the baryon fraction taken from Benitez-Llambay+. This doesn't appear to translate to the desired boundary condition that at large radii, the density should approach the mean background value of 10^(-6.7) cm^(-3).

This PR adds an (optional) different normalisation where the outermost radial coordinate has its density set to be the mean density. To make this assumption work, the outermost coordinate has been increased to 100*Rvir.

### CODE REVIEW

**Comment by rcooke-ast** [comment]
Thanks for the PR, Calvin!

I'm happy to merge this once I understand it a little better. I have a few questions:

(1) I'm not sure where the 10^-6.7 comes from as a background density. This should depend on cosmology, so maybe we should write this in more explicitly?
(2) It seems that the density profile is being scaled at 100 r_vir. I'm not sure why this would be. In fact, I imagine the final result will depend on the value adopted here. For example, if we instead use 200 r_vir, would the density profile still look the same in the inner 100 r_vir?
(3) A few binary files crept into the PR. Is it possible to remove them before we merge?

Also, I think this is a little different to the [Sternberg et al. (2002)](http://adsabs.harvard.edu/abs/2002ApJS..143..419S) approach, which you may like to look at.

Thanks again!

**Comment by rcooke-ast** [comment]
Oops, I only just realised that this has already been merged, sorry!

I'm still keen to understand your approach though, if you don't mind answering the few questions above?

Thanks!

**Comment by calvin-sykes** [comment]
This was just merging into my development branch - I definitely wouldn't assume that any of my changes are ready to go back into master!

I took the background density from [this paper](http://adsabs.harvard.edu/abs/2017MNRAS.465.3913B) (the same source you use for the baryon fractions), but you're right that it should be specified based on the cosmology. I had a go with the values they use and it seems about right:
```

G = 6.674e-8
mp = 1.673e-24
cm_per_pc = 3e10 * 86400 * 365 * 3.26

h = 0.704
omegab = 0.0455
prim_He = 1/12

rhocrit = 3 * (100 * h * 1e5 / (cm_per_pc * 1e6))**2 / (8 * np.pi * G)
nbaryon = omegab * rhocrit / (mp * (1 + 4 * prim_He)
np.log10(nbaryon) # = -6.721
```

The idea is that at "large enough" radius, the gas density should approach the background value - since it's flat after that, the inner shape of the profile shouldn't depend on exactly where the normalisation happens.
I picked 100Rvir by trying a few values and looked at the density profiles - there's a discontinuity in drho/dr at the scaling radius if it's too small i.e. the profile is being normalised before getting to the flat part.

I'd come across the Sternberg paper before - they talk about solving the pressure profile (their Eq 21/ your pressure_NFW function) subject to a condition that at some radius the pressure in the halo becomes equal to the external IGM pressure - this is a similar idea, but using the density.

Hope this helps!

**Comment by rcooke-ast** [comment]
Ahh.. you're quite right - sorry I thought this was a PR into the master branch. No problems!

Thanks for the explanations!

**Pull request merged**
